apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocumplidos-deployment
spec:
  replicas: 1  # Ajusta el número de réplicas según sea necesario
  selector:
    matchLabels:
      app: nocumplidos
  template:
    metadata:
      labels:
        app: nocumplidos
    spec:
      containers:
        - name: nocumplidos
          image: tu-repositorio/nocumplidos:etiqueta
          ports:
            - containerPort: 3000  # Puerto en el que escucha tu aplicación
